name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker (ensure Docker is available on the runner)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t zwemo:latest .

      # Step 4: Run the Docker container (useful for testing the image)
      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name zwemo_container zwemo:latest
          
      # Optional: Check that the container is running
      - name: Verify Docker container is running
        run: |
          docker ps
